# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: k8sgpt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'k8sgpt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ck8sgpt.proto\x12\tschema.v1\"\xcd\x01\n\x0e\x41nalyzeRequest\x12\x0f\n\x07\x62\x61\x63kend\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0f\n\x07\x65xplain\x18\x03 \x01(\x08\x12\x11\n\tanonymize\x18\x04 \x01(\x08\x12\x0f\n\x07nocache\x18\x05 \x01(\x08\x12\x10\n\x08language\x18\x06 \x01(\t\x12\x17\n\x0fmax_concurrency\x18\x07 \x01(\x05\x12\x0e\n\x06output\x18\x08 \x01(\t\x12\x0f\n\x07\x66ilters\x18\t \x03(\t\x12\x16\n\x0elabel_selector\x18\n \x01(\t\"\x88\x01\n\x0f\x41nalyzeResponse\x12\x1f\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x10.schema.v1.Error\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08problems\x18\x04 \x01(\x05\x12\"\n\x07results\x18\x05 \x03(\x0b\x32\x11.schema.v1.Result\"&\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"s\n\x06Result\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x05\x65rror\x18\x03 \x03(\x0b\x32\x16.schema.v1.ErrorDetail\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x15\n\rparent_object\x18\x05 \x01(\t\"H\n\x0b\x45rrorDetail\x12\x0c\n\x04text\x18\x01 \x01(\t\x12+\n\tsensitive\x18\x02 \x03(\x0b\x32\x18.schema.v1.SensitiveData\"1\n\rSensitiveData\x12\x10\n\x08unmasked\x18\x01 \x01(\t\x12\x0e\n\x06masked\x18\x02 \x01(\t2Y\n\x15ServerAnalyzerService\x12@\n\x07\x41nalyze\x12\x19.schema.v1.AnalyzeRequest\x1a\x1a.schema.v1.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'k8sgpt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=233
  _globals['_ANALYZERESPONSE']._serialized_start=236
  _globals['_ANALYZERESPONSE']._serialized_end=372
  _globals['_ERROR']._serialized_start=374
  _globals['_ERROR']._serialized_end=412
  _globals['_RESULT']._serialized_start=414
  _globals['_RESULT']._serialized_end=529
  _globals['_ERRORDETAIL']._serialized_start=531
  _globals['_ERRORDETAIL']._serialized_end=603
  _globals['_SENSITIVEDATA']._serialized_start=605
  _globals['_SENSITIVEDATA']._serialized_end=654
  _globals['_SERVERANALYZERSERVICE']._serialized_start=656
  _globals['_SERVERANALYZERSERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
